fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/nanliu/puppet-staging"
  symlinks:
    mysql_java_connector: "#{source_dir}"
